// models/game.ts
import mongoose, { Schema, Document, models } from "mongoose";

export interface IGame extends Document {
  walletAddress: string;
  gameHash: string;
  serverSeedHash: string; // Hash of server seed (revealed before game)
  serverSeed?: string; // Actual server seed (only revealed after game ends)
  clientSeed: string; // Auto-generated by server
  minePositions: number[];
  mineCount: number;
  mode: string;
  betAmount: number;
  status: 'playing' | 'won' | 'lost' | 'cashed_out';
  multiplier?: number;
  revealedSafeTiles?: number;
  createdAt: Date;
  endedAt?: Date;
}

const gameSchema = new Schema<IGame>(
  {
    walletAddress: { type: String, required: true, index: true },
    gameHash: { type: String, required: true, unique: true },
    serverSeedHash: { type: String, required: true },
    serverSeed: { type: String }, // Only set after game ends
    clientSeed: { type: String, required: true },
    minePositions: { type: [Number], required: true },
    mineCount: { type: Number, required: true },
    mode: { type: String, required: true },
    betAmount: { type: Number, required: true },
    status: { 
      type: String, 
      enum: ['playing', 'won', 'lost', 'cashed_out'],
      default: 'playing'
    },
    multiplier: { type: Number },
    revealedSafeTiles: { type: Number, default: 0 },
    endedAt: { type: Date },
  },
  { timestamps: true }
);

// Index for finding active games
gameSchema.index({ walletAddress: 1, status: 1 });

const Game = models.Game || mongoose.model<IGame>("Game", gameSchema);
export default Game;

